
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const REMOVE_TO_CART_REQUEST = "REMOVE_TO_CART_REQUEST";
export const PRODUCT_QTY_REQUEST = "PRODUCT_QTY_REQUEST";
export const PROCESS_DONE_REQUEST = " PROCESS_DONE_REQUEST";